{{- if .Values.gcp.enabled }}
kind: Secret
apiVersion: v1
metadata:
{{- if .Values.gcp.svcAccSecretCustomName }}
  name: {{ .Values.gcp.svcAccSecretCustomName }}
{{- else }}
  name: {{ include "sops-secrets-operator.name" . }}-gcp-secret
{{- end }}
  labels:
{{ include "sops-secrets-operator.labels" . | indent 4 }}
type: Opaque
stringData:
  key.json: |-
{{ .Values.gcp.svcAccSecret | indent 4 }}
{{- end }}
