{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sops-secrets-operator.fullname" . }}
  labels:
{{ include "sops-secrets-operator.labels" . | indent 4 }}
{{- end }}
