apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sopssecrets.isindir.github.com
spec:
  group: isindir.github.com
  names:
    kind: SopsSecret
    listKind: SopsSecretList
    plural: sopssecrets
    singular: sopssecret
    shortNames:
      - sops
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            secret_templates:
              type: array
              minLength: 1
              items:
                properties:
                  name:
                    type: string
                  annotations:
                    type: object
                  labels:
                    type: object
                  data:
                    type: object
        sops:
          type: object
          properties:
            kms:
              type: array
              items:
                properties:
                  arn:
                    type: string
                  created_at:
                    type: string
                  enc:
                    type: string
                  aws_profile:
                    type: string
            pgp:
              type: array
            gcp_kms:
              type: array
            azure_kv:
              type: array
            lastmodified:
              type: string
            mac:
              type: string
            version:
              type: string
            encrypted_suffix:
              type: string
            status:
              type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
