apiVersion: v1
version: 0.1.8
appVersion: 0.0.9
description: sops secrets operator
name: sops-secrets-operator
sources:
- https://github.com/isindir/sops-secrets-operator.git
maintainers:
- name: isindir
  email: isindir@users.sf.net
