apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: sopssecret-sample
spec:
  secretTemplates:
    - name: my-secret-name-0
      labels:
        label0: value0
        labelK: valueK
      annotations:
        key0: value0
        keyN: valueN
      stringData:
        data-name0: data-value0
        data-nameL: data-valueL
    - name: my-secret-name-1
      labels:
        label1: value1
      annotations:
        key1: value1
      data:
        data-name1: ZGF0YS12YWx1ZTE=
        data-nameM: ZGF0YS12YWx1ZU0=
      stringData:
        data-name0: data-value0
    - name: my-secret-name-2
      labels:
        label1: value1
      annotations:
        key1: value1
      data:
        data-name1: ZGF0YS12YWx1ZTE=
        data-nameM: ZGF0YS12YWx1ZU0=
    - name: jenkins-secret
      labels:
        "jenkins.io/credentials-type": "usernamePassword"
      annotations:
        "jenkins.io/credentials-description" : "credentials from Kubernetes"
      stringData:
        username: myUsername
        password: 'Pa$$word'
    - name: docker-login
      type: 'kubernetes.io/dockerconfigjson'
      stringData:
        .dockerconfigjson: '{"auths":{"index.docker.io":{"username":"imyuser","password":"mypass","email":"myuser@abc.com","auth":"aW15dXNlcjpteXBhc3M="}}}'
