apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: test-sopssecret-01
    namespace: default
spec:
    secretTemplates:
        - name: test-labels-annotations-jenkins-secret-01
          labels:
            jenkins.io/credentials-type: usernamePassword
          annotations:
            jenkins.io/credentials-description: credentials from Kubernetes
          stringData:
            username: myUsername
            password: Pa58163word
