apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: test-sopssecret-02
    namespace: default
spec:
    secretTemplates:
        - name: not-owned-secret-02
          stringData:
            username: myUsername
            password: Pa58163word
