apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: test-sopssecret-03
    namespace: default
spec:
    enforceOwnership: true
    secretTemplates:
        - name: previously-owned-secret-03
          stringData:
            username: myUsername
            password: Pa58163word
