apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: test-sopssecret-03
    namespace: default
spec:
    enforceOwnership: true
    secretTemplates:
        - name: ENC[AES256_GCM,data:2aVAJ8OJT6DVnPMKKYbr6cyLxpwnr384xYc=,iv:lA0HniykiHlb3gdEjdijaqemrLqOut1tRt0zjQJNzWQ=,tag:UKwQ+LX22m1l4b1KzA6mCg==,type:str]
          stringData:
            username: ENC[AES256_GCM,data:J4q44XBcbzI6hw==,iv:0llgFiqvCWsBtGnvNS6JBY2er8nStz3Ddk1bF1WwPuY=,tag:TUg4TNdyVHYG3CLhoZLauA==,type:str]
            password: ENC[AES256_GCM,data:NYNc89DFbzKrbdA=,iv:CQfkZiTO0YfkON+ZW0jNrtaIlxN6aVO584e7BMaDVfU=,tag:tRI5RYigYIcxgzl25sj7Hg==,type:str]
sops:
    age:
        - recipient: age1pnmp2nq5qx9z4lpmachyn2ld07xjumn98hpeq77e4glddu96zvms9nn7c8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWHFBNEJTeXVPcXRiZU5r
            NmRtbTN5N0I1cVV5ZW5CQkdqazNNTStqZXpVCkwrcTV0OGZ4RTlRenUycGp2QlVF
            M29vdDhoZE9URi9GNjhabHhkNzdhQ28KLS0tIHVvYlZLRnU4cklSdGdrU1VMa0R0
            MTE4M0VNUlptcFJtelY1VmM0czI0MVUKRUi17d/YIRtMy0Hy/F8NnzdcB//7y6Lo
            r98xMtafWDdCmtFLJ0ZgXg7ocEi0PgA+X5YNGXWTVcJGww2EFo3jFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T09:47:06Z"
    mac: ENC[AES256_GCM,data:AZFWZ4yyKlcq4K155d0iVM1BIeg+3XQ9XfZm1xH0ey4ggasyahEaVT44mCXQIAnuSeVrQDKrYdKigNejD0l5c0zeBsehiQqy4lxJ+rCADonVrCmSVYGOxLQ7Io8UwUh0jPQVbHcdwTr3W7vyQwb7H4vlXZYLDsJ0QxEwsSaL1fI=,iv:Yrqu9ZKioJu9l3Jnzrk25Rq4bs7iRa0pa/Pdv0XpPA4=,tag:RH3QN77b477R1txQT8htSw==,type:str]
    encrypted_suffix: Templates
    version: 3.12.1
