apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: test-sopssecret-04
  namespace: default
spec:
  secretTemplates:
    - name: test-mac-only-token
      stringData:
        token: macOnlyEncryptedPlaintextValue1234567890
