apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: test-sopssecret-04
    namespace: default
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:OcyTasfKtIVgxavKKM1sW1IWoQ==,iv:wgSlifca2Nc7PRjJjkzPyGjLsKJCkCwEsdubHOHc1D8=,tag:A4+F88r1xmBLZUJqkMkNbA==,type:str]
          stringData:
            token: ENC[AES256_GCM,data:fDRrIcURKBwHHAp5mb7SEpf78NseoQZPNDiRdzpoGGAxcZAmAqdAVQ==,iv:2+TNgi1ZTr5ZOILCzSHFTesfu4jcZGEHXmYOj4FNu/c=,tag:wCR83AguSKS48f4zrbEvMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaDRxdEtjNnU3d3pGMXhL
            VWZrK2c5dktIU2RmMnF0ckFIYjVpY2dTajN3Ci9jL1VMME5ueWdzamtIa05JOGVG
            UU1nV3dPR29pZ05zdkx6azBuUVoxTmcKLS0tIFFPQ0RXMHBjcDd5bXVna211UVBL
            clRObjI2MVMreHhLMUd0emc2ZFZxbmMKHW3Ou7Jk7r8OXJMnAiL8aWV3uBn6ojji
            r/+OOd6RDQipWE7E0U1+tE6rj+Dpj6mpreoZLYroDAMs8xAulXUOww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pnmp2nq5qx9z4lpmachyn2ld07xjumn98hpeq77e4glddu96zvms9nn7c8
    encrypted_suffix: Templates
    lastmodified: "2026-06-20T08:09:02Z"
    mac: ENC[AES256_GCM,data:t8hic3QulKbFprmQVsdlUbmFdoFA3WoCE66xdViL7PJ7+I59XEaaFBKswkJ37ED102T4itJwo8OiHR5YSNF8UR9eTDmBUShKITvTYdKmv44/VE6MURjhSCyuPhq91DtZO2geyL13xUJwc4/X5LpfNz/rym8YldfKiHt+hwxYrF4=,iv:zJ+DjrC0Pwly1NfmIhpeO41c2fJhod6a1QlXNX4x9ss=,tag:eX0ej21SKCS+oxoDqTuC/w==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
