apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: test-sopssecret-05
  namespace: default
spec:
  secretTemplates:
    - name: test-partially-encrypted-05
      stringData:
        LOG_LEVEL: debug
        WEB_CONCURRENCY: '4'
        OTEL_EXPORTER_OTLP_ENDPOINT: https://otel.example.com:4318
        DATABASE_URL: postgres://app:s3cr3t@db.example.com:5432/app
        OPENAI_API_KEY: sk-example-not-a-real-key
