apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: test-sopssecret-05
    namespace: default
spec:
    secretTemplates:
        - name: test-partially-encrypted-05
          stringData:
            LOG_LEVEL: debug
            WEB_CONCURRENCY: "4"
            OTEL_EXPORTER_OTLP_ENDPOINT: https://otel.example.com:4318
            DATABASE_URL: ENC[AES256_GCM,data:CQyw/4a70BVSZUFngkJvma9xQ+qMHN4M31JQjxyJsNco6qrJOHikI50TTBk0,iv:uI2dSuBfivmf5l8T9Log2tJhf0Hk5EkGzPtTNirgZ1o=,tag:k6Y3wqERGn/q0jI/CxN/kg==,type:str]
            OPENAI_API_KEY: ENC[AES256_GCM,data:kz4L5W7UxqvAmgYX+wqz8gKLS7fqxH/6aA==,iv:YOnuBS/GE0Vh/eDPXJ+Moff6aLdLrzguYoavHZuF0Ts=,tag:WfGhk6A9irlsH29ukne/DA==,type:str]
sops:
    age:
        - recipient: age1pnmp2nq5qx9z4lpmachyn2ld07xjumn98hpeq77e4glddu96zvms9nn7c8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UVNRQndjb2EvRE9VeTht
            Z3VOQk1CZzJzbnAzZ0w2RUFYbzBSZEhrWFUwCmJ4bXYvTmE3TFh2cWx0WUhSTU9O
            T3kxNUhLU0dPNFhDL0MyUXpaN3Zxdm8KLS0tIDF1ejFScXNzeXZVWk9McGRmV3Rx
            ZlNOdUY1STloRGRROVlEUzNhaStxMkEKgnOsfejFz3jA5LAY6EaOx8M+OQh8aW/X
            +h1FAutG0JK+f6M6+VcgWaf/NSYt/HaBw5ceRSCypIo45xFpjp0uIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-12T23:37:17Z"
    mac: ENC[AES256_GCM,data:pSIBremiYHR4JLtZSY9/ffDBaKw36Jzk76daTPr0HoW1blw2KgH+yNnN+nfNVZQVhPd6qMfBtca4taxazViIKhcIrMVJjRRmEJEj9wpmvn3PsQ1sLUA7ZgC2SNUhSN/69NmuyapOySFv0XJGqgM8qO3upwgOqg2XUBF1wIY5mjk=,iv:TPWHTIqjKyTxpPpwnv28wvQnzzDkiks9QWg0ih6UPR4=,tag:83xW0v2bSZT9TA//6OMY1A==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|status|name|LOG_LEVEL|WEB_CONCURRENCY|OTEL_EXPORTER_OTLP_ENDPOINT)$
    version: 3.11.0
