{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sops-secrets-operator.fullname" . }}-mentrics-monitor
  labels:
{{ include "sops-secrets-operator.labels" . | indent 4 }}
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sops-secrets-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
