style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/isindir/sops-secrets-operator
options:
  commits:
    filters:
      Type:
        - doc
        - docs
        - feat
        - fix
        - perf
        - pipe
        - refactor
        - up
        - update
        - upgrade
  commit_groups:
    title_maps:
      doc: Documentation Update
      docs: Documentation Update
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      pipe: Pipeline changes
      refactor: Code Refactoring
      up: Component Upgrade
      update: Component Upgrade
      upgrade: Component Upgrade
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
