// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/isindir/sops-secrets-operator/pkg/apis/isindir/v1alpha1.SopsSecret":       schema_pkg_apis_isindir_v1alpha1_SopsSecret(ref),
		"github.com/isindir/sops-secrets-operator/pkg/apis/isindir/v1alpha1.SopsSecretSpec":   schema_pkg_apis_isindir_v1alpha1_SopsSecretSpec(ref),
		"github.com/isindir/sops-secrets-operator/pkg/apis/isindir/v1alpha1.SopsSecretStatus": schema_pkg_apis_isindir_v1alpha1_SopsSecretStatus(ref),
	}
}

func schema_pkg_apis_isindir_v1alpha1_SopsSecret(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SopsSecret is the Schema for the sopssecrets API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/isindir/sops-secrets-operator/pkg/apis/isindir/v1alpha1.SopsSecretSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/isindir/sops-secrets-operator/pkg/apis/isindir/v1alpha1.SopsSecretStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/isindir/sops-secrets-operator/pkg/apis/isindir/v1alpha1.SopsSecretSpec", "github.com/isindir/sops-secrets-operator/pkg/apis/isindir/v1alpha1.SopsSecretStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_isindir_v1alpha1_SopsSecretSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SopsSecretSpec defines the desired state of SopsSecret",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_isindir_v1alpha1_SopsSecretStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SopsSecretStatus defines the observed state of SopsSecret",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
