// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureKmsItem) DeepCopyInto(out *AzureKmsItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureKmsItem.
func (in *AzureKmsItem) DeepCopy() *AzureKmsItem {
	if in == nil {
		return nil
	}
	out := new(AzureKmsItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcpKmsDataItem) DeepCopyInto(out *GcpKmsDataItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcpKmsDataItem.
func (in *GcpKmsDataItem) DeepCopy() *GcpKmsDataItem {
	if in == nil {
		return nil
	}
	out := new(GcpKmsDataItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmsDataItem) DeepCopyInto(out *KmsDataItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmsDataItem.
func (in *KmsDataItem) DeepCopy() *KmsDataItem {
	if in == nil {
		return nil
	}
	out := new(KmsDataItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgpDataItem) DeepCopyInto(out *PgpDataItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgpDataItem.
func (in *PgpDataItem) DeepCopy() *PgpDataItem {
	if in == nil {
		return nil
	}
	out := new(PgpDataItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsMetadata) DeepCopyInto(out *SopsMetadata) {
	*out = *in
	if in.AwsKms != nil {
		in, out := &in.AwsKms, &out.AwsKms
		*out = make([]KmsDataItem, len(*in))
		copy(*out, *in)
	}
	if in.Pgp != nil {
		in, out := &in.Pgp, &out.Pgp
		*out = make([]PgpDataItem, len(*in))
		copy(*out, *in)
	}
	if in.AzureKms != nil {
		in, out := &in.AzureKms, &out.AzureKms
		*out = make([]AzureKmsItem, len(*in))
		copy(*out, *in)
	}
	if in.GcpKms != nil {
		in, out := &in.GcpKms, &out.GcpKms
		*out = make([]GcpKmsDataItem, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsMetadata.
func (in *SopsMetadata) DeepCopy() *SopsMetadata {
	if in == nil {
		return nil
	}
	out := new(SopsMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsSecret) DeepCopyInto(out *SopsSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	in.Sops.DeepCopyInto(&out.Sops)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsSecret.
func (in *SopsSecret) DeepCopy() *SopsSecret {
	if in == nil {
		return nil
	}
	out := new(SopsSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SopsSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsSecretList) DeepCopyInto(out *SopsSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SopsSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsSecretList.
func (in *SopsSecretList) DeepCopy() *SopsSecretList {
	if in == nil {
		return nil
	}
	out := new(SopsSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SopsSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsSecretSpec) DeepCopyInto(out *SopsSecretSpec) {
	*out = *in
	if in.SecretsTemplate != nil {
		in, out := &in.SecretsTemplate, &out.SecretsTemplate
		*out = make([]SopsSecretTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsSecretSpec.
func (in *SopsSecretSpec) DeepCopy() *SopsSecretSpec {
	if in == nil {
		return nil
	}
	out := new(SopsSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsSecretStatus) DeepCopyInto(out *SopsSecretStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsSecretStatus.
func (in *SopsSecretStatus) DeepCopy() *SopsSecretStatus {
	if in == nil {
		return nil
	}
	out := new(SopsSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsSecretTemplate) DeepCopyInto(out *SopsSecretTemplate) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsSecretTemplate.
func (in *SopsSecretTemplate) DeepCopy() *SopsSecretTemplate {
	if in == nil {
		return nil
	}
	out := new(SopsSecretTemplate)
	in.DeepCopyInto(out)
	return out
}
