name: reviewdog
on: [pull_request]

jobs:
  golangci-lint:
    name: runner / golangci-lint
    # UPDATE_HERE
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-22.04
    steps:
      # UPDATE_HERE
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      # UPDATE_HERE
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: "--timeout=4m"

      # UPDATE_HERE
      - name: action-lint
        uses: reviewdog/action-actionlint@v1

      # UPDATE_HERE
      - name: docker hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          hadolint_flags: --trusted-registry docker.io
