name: reviewdog
on: [pull_request]

jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: "--timeout=4m"

      - name: action-lint
        uses: reviewdog/action-actionlint@v1

      - name: docker hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          hadolint_flags: --trusted-registry docker.io
